### ISSUE TITLE
Split "Hold notes" option in to two

### ISSUE THREAD

**Issue by parulina** [BardMusicPlayer/BardMusicPlayer#12]
"Hold notes" is kind of confusing since it does two things. Split it up and check on what to do with it.

- "Hold notes": make it toggle whether the game holds the notes for you or not. Just in case you want to play flute, but don't want them to be held.

- "Use synchronized key": switch between using async or sync keys, as potato pcs might perform better with this on

**Comment by troy-f** [comment]
Closing as this will be handled differently in 2.0
