### ISSUE TITLE
Cosmetic - Scale out of range / no notes text in Local Orchestra mode

### ISSUE THREAD

**Issue by Meowchestra** [BardMusicPlayer/BardMusicPlayer#25]
BardMusicPlayer compiled as of commit 012f81c with PR 19

Text for "All notes out of range." & "No notes playing on this track." need to be scaled properly so the text is actually readable in Local Orchestra mode instead of being cut off.

![link](https://i.imgur.com/ndyXKCR.png)

https://github.com/parulina/bardmusicplayer/blob/master/FFBardMusicPlayer/Controls/BmpKeyboard.cs#L90

**Comment by troy-f** [comment]
Closing as this doesn't apply to 2.0
