### ISSUE TITLE
Raise compiled executable privileges to run as Administrator

### ISSUE THREAD

**Issue by Meowchestra** [BardMusicPlayer/BardMusicPlayer#26]
BardMusicPlayer compiled as of commit 012f81c with PR 19

If you do not use an external launcher (FFXIVQuickLauncher) to open FFXIV, BMP is unable to detect character names and cannot read process memory. Custom launchers seem to bypass memory protection, but not everyone may use QuickLauncher.

![link1](https://i.imgur.com/vbOSYNP.png) ![link2](https://i.imgur.com/j5gEHt4.png)

The common workaround / fix is to just right click and run BMP as Administrator when using the vanilla launcher. _However_, is it possible to change the compiled executable to have raised privileges by default or check/request it?

---

Possible solution is to embed an app.manifest file with request privileges?

**Run as administrator if available and support normal launching if not;**
```xml
<requestedExecutionLevel level="highestAvailable" uiAccess="false" />
```

**Or just force require admin for memory reading instead;**
```xml
 <requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
```

Requiring admin privileges could also perhaps allow for future improvements with writing note playback directly to memory for faster / more accurate playing or even to prevent held notes that cause bards to fly away from keys not being released.

**Comment by MoogleTroupe** [comment]
Memory read operations are currently being extracted to a separate exe file which has the requestedExecutionLevel set. When that is complete the main bmp program will run as is, and a UAC prompt will automatically trigger only for the memory reading exe, which will talk to bmp over a named pipe.

**Comment by troy-f** [comment]
This has been added to 1.25 and 1.3
