### ISSUE TITLE
Cosmetic - Rotation order or more transition colors to FlashingTimer to make it appear less erratic

### ISSUE THREAD

**Issue by Meowchestra** [BardMusicPlayer/BardMusicPlayer#27]
BardMusicPlayer compiled as of commit 012f81c with PR 19

Very minor complaint, but would it be possible to add an actual color rotation or more colors when transitioning to the rainbow song select bar to make it appear less erratic?

https://github.com/parulina/bardmusicplayer/blob/85ec9e9ce64357284909f409d1afcfa9bb108fa0/FFBardMusicPlayer/Controls/BmpExplorer.cs#L36-L42

**Recording:** https://streamable.com/7oz892

**Comment by MoogleTroupe** [comment]
@Meowchestra https://github.com/parulina/bardmusicplayer/commit/8fc3a334a34a2f3ceb2555f4f0a4828e1bb3ea57

can you pick colors and PR, I just put in a simple triadic list.

**Comment by Meowchestra** [comment]
@MoogleTroupe The rotation itself is still erratic, it just flips between 3 colors now. It's like the fps of the application jumps around. The rotation is smooth and consistent for a few frames and then flips to going super fast like the timer or clock is catching up, speeding through the rotation instead of the same display duration for each color frame.

https://streamable.com/9medqu

**Comment by troy-f** [comment]
Closing as this doesn't apply to 2.0
