### ISSUE TITLE
Standart Orchestra Upgrade

### ISSUE THREAD

**Issue by TerminatorTM** [BardMusicPlayer/BardMusicPlayer#42]
From Manual: "Then, the party leader can start an ensemble request that each member will have to accept. A countdown will happen, and each bard will have to press Play (or space bar) at the same time when the metronome reaches 0."

I propose we implement one little modification based on old conductor mode (actually only on "read chat" part of it):
Add checkbox "Ensemble Start" in BMP. If checked - the program will wait for specific string in ingame chat and start playback with a delay of 5 sec after string is found.
String is system message "All party members are ready. The count-in will now commence.", generated by game after everybody press "ready" on ingame ensemble request.

It will be a great help for standard orchestra with minimum coding efforts. Can we have it please?

**Comment by troy-f** [comment]
BMP 2.0 will have automated syncing support which replaces what you are asking for.
